apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  DB_HOST: "<your-mysql-server>.mysql.database.azure.com"
  DB_USER: "<username>@<your-mysql-server>"
  DB_PASS: "<password>"
  DB_NAME: "apexdb"
