apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  DB_HOST: "myappdb.postgres.database.azure.com"
  DB_USER: "azurebdadmin@myappdb"
  DB_PASS: "Alere@1940"
  DB_NAME: "myappdb"
